create TABLE FILMS (
film_id LONG GENERATED BY DEFAULT AS INDENTITY PRIMARY KEY,
name varchar(100) NOT NULL,
description varchar(200) NOT NULL,
genre_id LONG REFERENCES genre_films (id) ON delete RESTRICT,
release_date date,
duration INTEGER,
rating_id LONG
);

create TABLE USERS (
user_id LONG GENERATED BY DEFAULT AS INDENTITY PRIMARY KEY,
name varchar(100) NOT NULL,
login varchar(200) NOT NULL,
email varchar(200) NOT NULL,
film_id LONG,
birthday date
);

create TABLE USER_FILM (
id LONG GENERATED BY DEFAULT AS INDENTITY PRIMARY KEY,
film_id LONG,
user_id LONG
);

create TABLE FRIENDS (
friend_id GENERATED BY DEFAULT AS INDENTITY PRIMARY KEY,
user_id LONG,
friendship BOOLEAN
);

create TABLE FILM_GENRE (
id GENERATED BY DEFAULT AS INDENTITY PRIMARY KEY,
genre_id LONG,
film_id LONG
);

create TABLE GENRE (
genre_id GENERATED BY DEFAULT AS INDENTITY PRIMARY KEY,
name varchar(100) NOT NULL,
last_update date
);

create TABLE RATING (
id GENERATED BY DEFAULT AS INDENTITY PRIMARY KEY,
name varchar (100) NOT NULL,
last_update date
);

insert into GENRE (name)
values ('COMEDY'),
 ('DRAMA'),
 ('CARTOON'),
 ('THRILLER'),
 ('DOCUMENTARY'),
 ('ACTION MOVIE');


insert into RATING (name)
values ('G'),
 ('PG'),
 ('PG-13'),
 ('R'),
 ('NC-17');



